import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowLeft, ArrowRight, Building2, CheckCircle2, HardHat, Loader2, LockKeyhole, Phone, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type View = "home" | "login" | "register";
type AccountRole = "MANAGER" | "WORKER";

export default function PhoneAuth() {
  const [view, setView] = useState<View>(() => {
    const requested = typeof window === "undefined" ? null : new URLSearchParams(window.location.search).get("auth");
    return requested === "login" || requested === "register" ? requested : "home";
  });
  const utils = trpc.useUtils();
  const afterAuth = async () => {
    await utils.auth.me.invalidate();
  };

  if (view === "login") return <Login onBack={() => setView("home")} onSuccess={afterAuth} />;
  if (view === "register") return <Register onBack={() => setView("home")} onSuccess={afterAuth} />;
  return <Welcome onLogin={() => setView("login")} onRegister={() => setView("register")} />;
}

function Welcome({ onLogin, onRegister }: { onLogin: () => void; onRegister: () => void }) {
  return <main className="min-h-screen overflow-hidden bg-[#173d38] text-white"><div className="relative mx-auto flex min-h-screen max-w-5xl flex-col justify-between px-6 pb-[max(1.75rem,env(safe-area-inset-bottom))] pt-[max(2rem,env(safe-area-inset-top))]"><div className="absolute -right-24 top-28 h-80 w-80 rounded-full border border-white/10" /><div className="absolute -right-10 top-44 h-56 w-56 rounded-full border border-[#f58252]/30" /><header className="relative flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e86f3e] shadow-lg shadow-black/20"><HardHat className="h-5 w-5" /></div><div><p className="font-extrabold tracking-[-0.04em]">Build On Works</p><p className="text-xs text-white/60">현장을 기반으로 사람과 일을 연결하다</p></div></header><section className="relative py-10"><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.22em] text-[#ffb18c]">Field workforce operations</p><h1 className="max-w-xl text-[3.25rem] font-extrabold leading-[.96] tracking-[-0.075em] sm:text-6xl">현장을<br />더 정확하게<br /><span className="text-[#ff9b70]">운영하세요.</span></h1><p className="mt-6 max-w-md text-[15px] leading-7 text-white/70">인력소장과 인부가 일감, 출퇴근, 급여를 각자의 역할에 맞게 간편하게 관리합니다.</p><div className="mt-9 grid max-w-xl grid-cols-3 gap-2.5"><Feature icon={Building2} text="인력소 운영" /><Feature icon={CheckCircle2} text="출퇴근 기록" /><Feature icon={ShieldCheck} text="권한별 관리" /></div></section><div className="relative grid gap-3 sm:max-w-md"><Button onClick={onLogin} className="h-14 rounded-2xl bg-[#e86f3e] text-base font-bold hover:bg-[#f58252]">로그인 <ArrowRight className="ml-2 h-4 w-4" /></Button><Button onClick={onRegister} variant="outline" className="h-14 rounded-2xl border-white/30 bg-white/5 text-base font-bold text-white hover:bg-white/10 hover:text-white">회원가입</Button><p className="pt-1 text-center text-[11px] text-white/52">전화번호와 비밀번호로 안전하게 로그인합니다.</p></div></div></main>;
}

function Login({ onBack, onSuccess }: { onBack: () => void; onSuccess: () => Promise<void> }) {
  const [phone, setPhone] = useState(""); const [password, setPassword] = useState("");
  const login = trpc.phoneAuth.login.useMutation({ onSuccess: async () => { toast.success("로그인 성공!"); await onSuccess(); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); login.mutate({ phone, password }); };
  return <AuthLayout eyebrow="전화번호 로그인" title={<>현장 계정으로<br />로그인하세요.</>} description="가입한 휴대폰 번호와 비밀번호를 입력해 주세요." onBack={onBack}><form onSubmit={submit} className="space-y-5"><AuthField icon={Phone} label="휴대폰 번호"><Input required value={phone} onChange={e => setPhone(formatPhoneInput(e.target.value))} inputMode="tel" placeholder="010-0000-0000" /></AuthField><AuthField icon={LockKeyhole} label="비밀번호"><Input required value={password} onChange={e => setPassword(e.target.value)} type="password" autoComplete="current-password" placeholder="비밀번호 입력" /></AuthField><Button disabled={login.isPending} className="h-13 w-full rounded-2xl bg-[#173d38] text-base font-bold hover:bg-[#0e2e2a]">{login.isPending ? <Loader2 className="animate-spin" /> : <>로그인 <ArrowRight className="ml-1 h-4 w-4" /></>}</Button></form></AuthLayout>;
}

function Register({ onBack, onSuccess }: { onBack: () => void; onSuccess: () => Promise<void> }) {
  const [role, setRole] = useState<AccountRole>("MANAGER"); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [birthDate, setBirthDate] = useState(""); const [certificate, setCertificate] = useState(""); const [bankName, setBankName] = useState("국민은행"); const [bankAccount, setBankAccount] = useState("");
  const register = trpc.phoneAuth.register.useMutation({ onSuccess: async () => { toast.success("회원가입이 완료되었습니다."); await onSuccess(); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (password !== confirm) { toast.error("비밀번호 확인이 일치하지 않습니다."); return; } register.mutate({ name, phone, password, accountRole: role, ...(role === "WORKER" ? { birthDate, certificate, bankName, bankAccount } : {}) }); };
  return <AuthLayout eyebrow="새 계정 만들기" title={<>역할에 맞게<br />시작하세요.</>} description="회원가입 후 바로 현장 운영 서비스를 사용할 수 있습니다." onBack={onBack}><form onSubmit={submit} className="space-y-5"><div className="grid grid-cols-2 gap-3"><RoleCard active={role === "MANAGER"} title="인력소장" text="인력소·일감·급여 관리" icon={Building2} onClick={() => setRole("MANAGER")} /><RoleCard active={role === "WORKER"} title="인부" text="일감·출퇴근·급여 확인" icon={HardHat} onClick={() => setRole("WORKER")} /></div><AuthField icon={HardHat} label="이름"><Input required value={name} onChange={e => setName(e.target.value)} placeholder="이름 입력" autoComplete="name" /></AuthField><AuthField icon={Phone} label="휴대폰 번호"><Input required value={phone} onChange={e => setPhone(formatPhoneInput(e.target.value))} inputMode="tel" placeholder="010-0000-0000" autoComplete="tel" /></AuthField><AuthField icon={LockKeyhole} label="비밀번호"><Input required value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="4자리 이상 입력" autoComplete="new-password" /></AuthField><AuthField icon={LockKeyhole} label="비밀번호 확인"><Input required value={confirm} onChange={e => setConfirm(e.target.value)} type="password" placeholder="비밀번호 다시 입력" autoComplete="new-password" /></AuthField>{role === "WORKER" ? <div className="rounded-[1.3rem] bg-[#f6f7f4] p-4"><p className="mb-3 text-sm font-bold">인부 추가 정보</p><div className="grid gap-3"><Input required type="date" value={birthDate} onChange={e => setBirthDate(e.target.value)} /><Input value={certificate} onChange={e => setCertificate(e.target.value)} placeholder="이수증 등록번호 (선택)" /><div className="grid grid-cols-2 gap-3"><select value={bankName} onChange={e => setBankName(e.target.value)} className="h-10 rounded-md border border-[#e3e6df] bg-white px-3 text-sm shadow-sm outline-none focus:border-[#d56835]"><option value="국민은행">국민은행</option><option value="신한은행">신한은행</option><option value="농협은행">농협은행</option><option value="우리은행">우리은행</option></select><Input value={bankAccount} onChange={e => setBankAccount(e.target.value)} inputMode="numeric" placeholder="계좌번호" /></div></div></div> : null}<Button disabled={register.isPending} className="h-13 w-full rounded-2xl bg-[#173d38] text-base font-bold hover:bg-[#0e2e2a]">{register.isPending ? <Loader2 className="animate-spin" /> : <>회원가입 완료 <ArrowRight className="ml-1 h-4 w-4" /></>}</Button></form></AuthLayout>;
}

function AuthLayout({ eyebrow, title, description, onBack, children }: { eyebrow: string; title: React.ReactNode; description: string; onBack: () => void; children: React.ReactNode }) { return <main className="min-h-screen bg-[#f7f5f0] px-5 pb-[max(2rem,env(safe-area-inset-bottom))] pt-[max(1.25rem,env(safe-area-inset-top))]"><div className="mx-auto max-w-md"><button onClick={onBack} className="mb-7 inline-flex h-10 items-center gap-1 rounded-xl px-2 text-sm font-bold text-[#53615a]"><ArrowLeft className="h-4 w-4" />처음으로</button><section className="rounded-[1.8rem] border border-[#1d2422]/5 bg-white p-6 shadow-xl shadow-[#153b36]/[0.07]"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#d56835]">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold leading-[1.05] tracking-[-0.06em]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#718079]">{description}</p><div className="mt-7">{children}</div></section></div></main>; }
function RoleCard({ active, title, text, icon: Icon, onClick }: { active: boolean; title: string; text: string; icon: typeof Building2; onClick: () => void }) { return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-left transition ${active ? "border-[#d56835] bg-[#fff4ed] shadow-sm" : "border-[#1d2422]/10 bg-[#fafaf8]"}`}><Icon className={`mb-4 h-5 w-5 ${active ? "text-[#d56835]" : "text-[#738078]"}`} /><p className="font-bold">{title}</p><p className="mt-1 text-[11px] leading-4 text-[#718079]">{text}</p></button>; }
function AuthField({ icon: Icon, label, children }: { icon: typeof Phone; label: string; children: React.ReactNode }) { return <label className="block space-y-2"><span className="flex items-center gap-1.5 text-xs font-bold text-[#4d5953]"><Icon className="h-3.5 w-3.5 text-[#d56835]" />{label}</span>{children}</label>; }
function Feature({ icon: Icon, text }: { icon: typeof Building2; text: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.06] px-2 py-4 text-center"><Icon className="mx-auto mb-2 h-4 w-4 text-[#ffb18c]" /><span className="text-[11px] font-bold">{text}</span></div>; }
function formatPhoneInput(value: string) { const digits = value.replace(/\D/g, "").slice(0, 11); if (digits.length <= 3) return digits; if (digits.length <= 7) return `${digits.slice(0, 3)}-${digits.slice(3)}`; return `${digits.slice(0, 3)}-${digits.slice(3, 7)}-${digits.slice(7)}`; }
